spring.application.name=RAG-With-WebSearch

logging.level.org.springframework.ai.chat.client.advisor=debug

spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=rag-with-web
spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.use-tls=false

spring.docker.compose.stop.command=DOWN

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.model=mxbai-embed-large
spring.ai.ollama.chat.model=llama3